version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: sizpay-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sizpay
    ports:
      - '5434:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d sizpay']
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: sizpay-redis
    ports:
      - '6379:6379'
    command: ["redis-server", "--save", "", "--appendonly", "no"]